name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
    with:
      path: |
        ~/.cargo/registry
        ~/.cargo/git
        target
      key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Checkout quizers
      uses: actions/checkout@v2
      with:
        path: ./quizers

    - name: Checkout md-questions
      uses: actions/checkout@v2
      with:
        repository: devzbysiu/md-questions
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        path: ./md-questions

    - name: Run cargo-make
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - name: Run tests
      run: cd ./quizers && cargo make --profile ci all
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
